jobs:
  deploy:
    working_dir: ~/python-ci
    docker: 
      - image: circleci/python:3.6.1
    steps: 
      - checkout
      - restore_cache:
          keys:
            - dependencies-node-{{ checksum "package.json" }}
            - dependencies-node
      - run:
          name: Install python dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Install node and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version && npm -v
      - run: 
          name: Install Serverless CLI and dependencies
          command: | 
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-node-{{ checksum "package.json" }}
- run:
          name: Deploy application
          command: sls deploy -v
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
